apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-cluster1-infra
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jjsadek/gloo-mesh-aoa/
    targetRevision: HEAD
    path: environments/cluster1/infra/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false